import type React from "react";
import type { GenerationType } from "../types.js";
import styles from "../css/theme.module.css";

type TypeInfo = {
  type: GenerationType;
  label: string;
  icon: string;
  summaryText: string;
  disclaimer: string;
  description: string;
  example: string;
};

const TYPE_REGISTRY: TypeInfo[] = [
  {
    type: "ai-generated",
    label: "AI Generated",
    icon: "🤖",
    summaryText: "AI-generated documentation",
    disclaimer:
      "This page was drafted by an AI assistant and may contain inaccuracies.",
    description:
      "Page drafted entirely by AI from codebase or prompt instructions.",
    example: "e.g., docs generated from codebase analysis",
  },
  {
    type: "ai-transformatted",
    label: "AI Transformatted",
    icon: "✋→🤖",
    summaryText: "AI-transformatted documentation",
    disclaimer:
      "This page was generated by AI from human-provided source material. It may contain inaccuracies.",
    description:
      "Human provided raw material; AI restructured it into a different format.",
    example: "e.g., livestream → blog post, meeting notes → docs",
  },
  {
    type: "human-generated",
    label: "Human Generated",
    icon: "✋",
    summaryText: "Human-generated documentation",
    disclaimer: "This page was written by a human contributor.",
    description: "Page written entirely by a human author.",
    example: "e.g., hand-written tutorial",
  },
];

const DEFAULT_MORE_INFO_URL =
  "https://docs.freemocap.org/skellydocs/docs/ai-generated-banner";

function getTypeInfo(generationType: string): TypeInfo {
  return (
    TYPE_REGISTRY.find((t) => t.type === generationType) ?? TYPE_REGISTRY[0]
  );
}

/**
 * Generation-type banner for doc pages. Collapsed by default.
 * Summary line shows generation type + optional curated badge.
 * Expanding reveals disclaimer, metadata, and a nested overview of all generation types.
 */
export default function AiGeneratedBanner({
  repo,
  generationType = "ai-generated",
  humanCurated = false,
  generatedAt,
  model,
  humanNotes,
  moreInfoUrl = DEFAULT_MORE_INFO_URL,
}: {
  repo?: string;
  generationType?: GenerationType;
  humanCurated?: boolean;
  generatedAt?: string;
  model?: string;
  humanNotes?: string;
  moreInfoUrl?: string;
}): React.ReactElement {
  const info = getTypeInfo(generationType);
  const issueUrl = repo
    ? `https://github.com/${repo}/issues/new?labels=documentation&template=docs-issue.md`
    : undefined;
  const hasMetadata = generatedAt || model;

  return (
    <details className={styles.aiBanner}>
      <summary className={styles.aiBannerSummary}>
        <span className={styles.aiBannerIcon}>{info.icon}</span>
        <span>{info.summaryText}</span>
        <span
          className={
            humanCurated
              ? styles.aiBannerCurated
              : styles.aiBannerCuratedEmpty
          }
        >
          {humanCurated ? "✓" : "☐"} curated
        </span>
        <span className={styles.aiBannerTypeBadge}>{info.label}</span>
      </summary>
      <div className={styles.aiBannerBody}>
        <span>
          {info.disclaimer}
          {humanCurated &&
            " This content has been reviewed by a human curator."}
          {issueUrl && (
            <>
              {" "}
              If you spot something wrong, please{" "}
              <a href={issueUrl}>open an issue</a> or use the{" "}
              <em>Edit this page</em> link below to submit a fix.
            </>
          )}
        </span>

        {hasMetadata && (
          <div className={styles.aiBannerDetailsList}>
            {generatedAt && (
              <span>
                <strong>Generated:</strong> {generatedAt}
              </span>
            )}
            {model && (
              <span>
                <strong>Model:</strong> {model}
              </span>
            )}
          </div>
        )}

        {humanNotes && (
          <div className={styles.aiBannerHumanNotes}>
            <strong>Curator notes:</strong> {humanNotes}
          </div>
        )}

        <details className={styles.aiBannerTypeOverview}>
          <summary className={styles.aiBannerTypeOverviewSummary}>
            About content generation types
          </summary>
          <div className={styles.aiBannerTypeList}>
            {TYPE_REGISTRY.map((entry) => (
              <div
                key={entry.type}
                className={`${styles.aiBannerTypeRow}${
                  entry.type === generationType
                    ? ` ${styles.aiBannerTypeRowActive}`
                    : ""
                }`}
              >
                <span className={styles.aiBannerTypeRowIcon}>
                  {entry.icon}
                </span>
                <div>
                  <strong>{entry.label}</strong> — {entry.description}
                  <br />
                  <span className={styles.aiBannerTypeExample}>
                    ({entry.example})
                  </span>
                </div>
                {entry.type === generationType && (
                  <span className={styles.aiBannerTypeRowCurrent}>
                    ← this page
                  </span>
                )}
              </div>
            ))}
          </div>
          {moreInfoUrl && (
            <a
              href={moreInfoUrl}
              className={styles.aiBannerMoreInfo}
              target="_blank"
              rel="noopener noreferrer"
            >
              More info about content generation types ↗
            </a>
          )}
        </details>
      </div>
    </details>
  );
}
