import type React from "react";
import type { GenerationType } from "../types.js";
import styles from "../css/theme.module.css";

const GENERATION_LABELS: Record<GenerationType, string> = {
  "ai-generated": "AI Generated",
  "ai-human-curated": "AI Generated / Human Curated",
  "human-sourced-ai": "Human-Sourced / AI Generated",
  "human-generated": "Human Generated",
};

const SUMMARY_ICONS: Record<GenerationType, string> = {
  "ai-generated": "🤖",
  "ai-human-curated": "🤖✋",
  "human-sourced-ai": "✋🤖",
  "human-generated": "✋",
};

const SUMMARY_TEXT: Record<GenerationType, string> = {
  "ai-generated": "AI-generated documentation",
  "ai-human-curated": "AI-generated, human-curated documentation",
  "human-sourced-ai": "Human-sourced, AI-generated documentation",
  "human-generated": "Human-generated documentation",
};

const DISCLAIMER_TEXT: Record<GenerationType, string> = {
  "ai-generated":
    "This page was drafted by an AI assistant and may contain inaccuracies.",
  "ai-human-curated":
    "This page was drafted by an AI assistant and reviewed by a human curator. It may still contain inaccuracies.",
  "human-sourced-ai":
    "This page was generated by AI from human-provided source material. It may contain inaccuracies.",
  "human-generated":
    "This page was written by a human contributor.",
};

/**
 * Generation-type banner for doc pages. Collapsed by default (like "About this roadmap").
 * Summary line adapts to the generation type. Expanding reveals details and issue link.
 */
export default function AiGeneratedBanner({
  repo,
  generationType = "ai-generated",
  generatedAt,
  model,
  humanNotes,
}: {
  repo: string;
  generationType?: GenerationType;
  generatedAt?: string;
  model?: string;
  humanNotes?: string;
}): React.ReactElement {
  const issueUrl = `https://github.com/${repo}/issues/new?labels=documentation&template=docs-issue.md`;
  const hasMetadata = generatedAt || model;

  return (
    <details className={styles.aiBanner}>
      <summary className={styles.aiBannerSummary}>
        <span className={styles.aiBannerIcon}>
          {SUMMARY_ICONS[generationType]}
        </span>
        <span>{SUMMARY_TEXT[generationType]}</span>
        <span className={styles.aiBannerTypeBadge}>
          {GENERATION_LABELS[generationType]}
        </span>
      </summary>
      <div className={styles.aiBannerBody}>
        <span>
          {DISCLAIMER_TEXT[generationType]}{" "}
          If you spot something wrong, please{" "}
          <a href={issueUrl}>open an issue</a> or use the{" "}
          <em>Edit this page</em> link below to submit a fix.
        </span>

        {hasMetadata && (
          <div className={styles.aiBannerDetailsList}>
            {generatedAt && (
              <span>
                <strong>Generated:</strong> {generatedAt}
              </span>
            )}
            {model && (
              <span>
                <strong>Model:</strong> {model}
              </span>
            )}
          </div>
        )}

        {humanNotes && (
          <div className={styles.aiBannerHumanNotes}>
            <strong>Curator notes:</strong> {humanNotes}
          </div>
        )}
      </div>
    </details>
  );
}
