#!/usr/bin/env node

/**
 * Regenerates the skellydocs-docs/ dogfood site from templates.
 *
 * This is the non-interactive equivalent of `npx skellydocs init` —
 * it uses the same Handlebars templates but skips the prompts so it
 * can run in CI or be called from `npm run rebuild-dogfood`.
 *
 * Usage:
 *   node scripts/rebuild-dogfood.mjs          # delete + regenerate
 *   node scripts/rebuild-dogfood.mjs --keep   # regenerate without deleting first
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Handlebars from "handlebars";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "..");
const TEMPLATES_DIR = path.join(PKG_ROOT, "templates");
const TARGET_DIR = path.join(PKG_ROOT, "skellydocs-docs");

function getOwnVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "package.json"), "utf-8"));
  return pkg.version;
}

const keepExisting = process.argv.includes("--keep");

// ── Template data (mirrors what the interactive CLI would collect) ──

const templateData = {
  projectName: "skellydocs",
  orgName: "freemocap",
  repo: "freemocap/skellydocs",
  repoUrl: "https://github.com/freemocap/skellydocs",
  projectUrl: "https://freemocap.github.io/skellydocs",
  editUrl: "https://github.com/freemocap/skellydocs/tree/main/skellydocs-docs/",
  siteUrl: "https://freemocap.github.io",
  baseUrl: "/skellydocs/",
  skellydocsVersion: getOwnVersion(),
  skellydocsDep: "file:..",
  isoDate: new Date().toISOString().slice(0, 10),
};

// ── Helpers ──

function renderTemplate(name) {
  const source = fs.readFileSync(path.join(TEMPLATES_DIR, name), "utf-8");
  return Handlebars.compile(source)(templateData);
}

function writeFile(filePath, content) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`  created ${path.relative(PKG_ROOT, filePath)}`);
}

function copyFile(src, dest) {
  const dir = path.dirname(dest);
  fs.mkdirSync(dir, { recursive: true });
  fs.copyFileSync(src, dest);
  console.log(`  created ${path.relative(PKG_ROOT, dest)}`);
}

// ── Main ──

if (!keepExisting && fs.existsSync(TARGET_DIR)) {
  console.log(`\nDeleting ${path.relative(PKG_ROOT, TARGET_DIR)}/...\n`);
  fs.rmSync(TARGET_DIR, { recursive: true, force: true });
}

console.log(`Scaffolding skellydocs-docs/...\n`);

// Config files
writeFile(
  path.join(TARGET_DIR, "package.json"),
  renderTemplate("package.json.hbs"),
);

writeFile(
  path.join(TARGET_DIR, "docusaurus.config.ts"),
  renderTemplate("docusaurus.config.ts.hbs"),
);

writeFile(
  path.join(TARGET_DIR, "content.config.tsx"),
  renderTemplate("content.config.tsx.hbs"),
);

writeFile(
  path.join(TARGET_DIR, "sidebars.ts"),
  `import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';\n\nconst sidebars: SidebarsConfig = {\n  docsSidebar: [{type: 'autogenerated', dirName: '.'}],\n};\n\nexport default sidebars;\n`,
);

writeFile(
  path.join(TARGET_DIR, "tsconfig.json"),
  JSON.stringify(
    { extends: "@docusaurus/tsconfig", compilerOptions: { baseUrl: "." } },
    null,
    2,
  ) + "\n",
);

// Content
writeFile(
  path.join(TARGET_DIR, "docs", "intro.mdx"),
  renderTemplate("docs/intro.mdx.hbs"),
);

writeFile(
  path.join(TARGET_DIR, "docs", "ai-generated-banner.mdx"),
  renderTemplate("docs/ai-generated-banner.mdx.hbs"),
);

writeFile(
  path.join(TARGET_DIR, "docs", "customizing-index-page.mdx"),
  renderTemplate("docs/customizing-index-page.mdx.hbs"),
);

writeFile(
  path.join(TARGET_DIR, "blog", `${templateData.isoDate}_welcome.mdx`),
  renderTemplate("blog/init.mdx.hbs"),
);

// Pages
const pagesDir = path.join(TARGET_DIR, "src", "pages");

writeFile(
  path.join(pagesDir, "index.tsx"),
  `import { IndexPage, HeroSection, FeaturesSection, GuaranteesSection } from '@freemocap/skellydocs';
import config from '../../content.config';

// Level 3 customization: compose from exported sub-components.
// Reorder sections, add your own components between them, or drop sections entirely.
// For a simpler setup, just use: <IndexPage config={config} />
export default function Home() {
  return (
    <IndexPage config={config}>
      <HeroSection config={config} />
      <FeaturesSection config={config} />
      <GuaranteesSection config={config} />
    </IndexPage>
  );
}
`,
);

writeFile(
  path.join(pagesDir, "roadmap.tsx"),
  `import { RoadmapPage, collectLinkedUrls } from '@freemocap/skellydocs';\nimport config from '../../content.config';\n\nconst REPO = '${templateData.repo}';\n\nexport default function Roadmap() {\n  return <RoadmapPage repo={REPO} pinnedIssues={collectLinkedUrls(config)} />;\n}\n`,
);

// Static assets
copyFile(
  path.join(TEMPLATES_DIR, "static", "img", "logo.svg"),
  path.join(TARGET_DIR, "static", "img", "logo.svg"),
);

console.log(`\n✅ skellydocs-docs/ rebuilt from templates.`);
console.log(`\n  Next steps:\n    npm install\n    npm start -w skellydocs-docs\n`);
